source 'https://github.com/CocoaPods/Specs.git'

target 'GhostLoginClient_Example', :exclusive => true do
  pod "GhostLoginClient", :path => "../"
end

target 'GhostLoginClient_Tests', :exclusive => true do
  pod "GhostLoginClient", :path => "../"
end
