source 'https://github.com/CocoaPods/Specs.git'

target 'GhostLoginClient_Example', :exclusive => true do
  pod "KMMGhostLoginClient", :path => "../"
end

target 'GhostLoginClient_Tests', :exclusive => true do
  pod "KMMGhostLoginClient", :path => "../"
  pod 'OCMockito', '~> 1.4'
  
end
